# Name of the executable
EXE=fastQValidator
########################
# The Files:
TOOLBASE = 
SRCONLY = FastQValidator.cpp
HDRONLY = 

########################
# Include the base Makefile
PARENT_MAKE = Makefile.src
include ../Makefile.inc
